In [1]:
import pandas as pd

In [2]:
a=[1,6,23,11]

In [3]:
myvar=pd.Series(a)

In [4]:
print(myvar)

0     1
1     6
2    23
3    11
dtype: int64


In [5]:
myvar=pd.Series(a,index=["a","b","c","d"])

In [6]:
print(myvar)

a     1
b     6
c    23
d    11
dtype: int64


In [7]:
print(myvar["a"])

1


In [8]:
data={
    "calories": [100,210,400],
    "age": [10,13,18]}
mydata=pd.DataFrame(data)

In [9]:
print(mydata)

   calories  age
0       100   10
1       210   13
2       400   18


In [10]:
import math

In [11]:
print(math.floor(3.6))

3


In [12]:
print(math.sqrt(4.0))

2.0


In [13]:
print(math.gcd(3,6))

3


In [14]:
import numpy as np
print(np.sort([8,2,12,4]))

[ 2  4  8 12]


In [15]:
arr=np.array([[1,4,6],[2,41,8]])
print(arr)

[[ 1  4  6]
 [ 2 41  8]]


In [16]:
arr=arr.reshape(3,2)
print(arr)

[[ 1  4]
 [ 6  2]
 [41  8]]


In [17]:
arr=np.sort(arr)
print(arr)

[[ 1  4]
 [ 2  6]
 [ 8 41]]


In [18]:
print(arr.shape)

(3, 2)


In [19]:
print(np.sum(arr))

62


In [20]:
print(math.isqrt(4))

2


In [21]:
from numpy import linalg as LA
array=LA.eigvals([[1,2],[4,6]])
print(array)

[-0.27491722  7.27491722]


In [22]:
df=pd.read_csv(r"C:\Users\student\Documents\Machine Learning\Housing.csv")
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [23]:
print(df["area"])

0      7420
1      8960
2      9960
3      7500
4      7420
       ... 
540    3000
541    2400
542    3620
543    2910
544    3850
Name: area, Length: 545, dtype: int64


In [24]:
ar1=np.array(df["area"])
print(ar1)

[ 7420  8960  9960  7500  7420  7500  8580 16200  8100  5750 13200  6000
  6550  3500  7800  6000  6600  8500  4600  6420  4320  7155  8050  4560
  8800  6540  6000  8875  7950  5500  7475  7000  4880  5960  6840  7000
  7482  9000  6000  6000  6550  6360  6480  6000  6000  6000  6000  6600
  4300  7440  7440  6325  6000  5150  6000  6000 11440  9000  7680  6000
  6000  8880  6240  6360 11175  8880 13200  7700  6000 12090  4000  6000
  5020  6600  4040  4260  6420  6500  5700  6000  6000  4000 10500  6000
  3760  8250  6670  3960  7410  8580  5000  6750  4800  7200  6000  4100
  9000  6400  6600  6000  6600  5500  5500  6350  5500  4500  5450  6420
  3240  6615  6600  8372  4300  9620  6800  8000  6900  3700  6420  7020
  6540  7231  6254  7320  6525 15600  7160  6500  5500 11460  4800  5828
  5200  4800  7000  6000  5400  4640  5000  6360  5800  6660 10500  4800
  4700  5000 10500  5500  6360  6600  5136  4400  5400  3300  3650  6100
  6900  2817  7980  3150  6210  6100  6600  6825  6

In [25]:
print(np.shape(ar1))

(545,)


In [29]:
mean=df["area"].mean()
median=df["area"].median()
print(mean)
print("Median:", median)


5150.54128440367
Median: 4600.0


In [30]:
var=df["area"].var()
std=df["area"].std()
print("Variance:", var)
print("Standard Deviation:", std)

Variance: 4709512.057575553
Standard Deviation: 2170.141022508803


In [34]:
filtereddf=df[df["area"]>7000]
print(filtereddf)

        price   area  bedrooms  bathrooms  stories mainroad guestroom  \
0    13300000   7420         4          2        3      yes        no   
1    12250000   8960         4          4        4      yes        no   
2    12250000   9960         3          2        2      yes        no   
3    12215000   7500         4          2        2      yes        no   
4    11410000   7420         4          1        2      yes       yes   
..        ...    ...       ...        ...      ...      ...       ...   
403   3500000  12944         3          1        1      yes        no   
452   3150000   9000         3          1        2      yes        no   
460   3087000   8100         2          1        1      yes        no   
473   3003000   8050         2          1        1      yes        no   
520   2450000   7700         2          1        1      yes        no   

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2    

In [35]:
merged_df=pd.merge(df,filtereddf,on='area')
print(merged_df)

      price_x  area  bedrooms_x  bathrooms_x  stories_x mainroad_x  \
0    13300000  7420           4            2          3        yes   
1    13300000  7420           4            2          3        yes   
2    12250000  8960           4            4          4        yes   
3    12250000  9960           3            2          2        yes   
4    12215000  7500           4            2          2        yes   
..        ...   ...         ...          ...        ...        ...   
145   3087000  8100           2            1          1        yes   
146   3003000  8050           2            1          1        yes   
147   3003000  8050           2            1          1        yes   
148   2450000  7700           2            1          1        yes   
149   2450000  7700           2            1          1        yes   

    guestroom_x basement_x hotwaterheating_x airconditioning_x  ...  \
0            no         no                no               yes  ...   
1            no  

In [36]:
merged_df=merged_df.dropna()

In [37]:
print(merged_df)

      price_x  area  bedrooms_x  bathrooms_x  stories_x mainroad_x  \
0    13300000  7420           4            2          3        yes   
1    13300000  7420           4            2          3        yes   
2    12250000  8960           4            4          4        yes   
3    12250000  9960           3            2          2        yes   
4    12215000  7500           4            2          2        yes   
..        ...   ...         ...          ...        ...        ...   
145   3087000  8100           2            1          1        yes   
146   3003000  8050           2            1          1        yes   
147   3003000  8050           2            1          1        yes   
148   2450000  7700           2            1          1        yes   
149   2450000  7700           2            1          1        yes   

    guestroom_x basement_x hotwaterheating_x airconditioning_x  ...  \
0            no         no                no               yes  ...   
1            no  

In [39]:
print(merged_df.shape)

(150, 25)


In [40]:
df["normalized"]=(df["area"] -df["area"].min())/(df["area"].max()-df["area"].min())
print(df["normalized"])

0      0.396564
1      0.502405
2      0.571134
3      0.402062
4      0.396564
         ...   
540    0.092784
541    0.051546
542    0.135395
543    0.086598
544    0.151203
Name: normalized, Length: 545, dtype: float64


In [45]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [48]:
x_scaled=scaler.fit_transform(dfnumeric)

In [49]:
dfnumeric=df.select_dtypes(include=['float64','int64'])

In [51]:
from sklearn.decomposition import PCA
pca2=PCA(n_components=3)
dfpca=pca2.fit_transform(dfnumeric)


In [1]:
from collections import Counter

In [ ]:
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((np.array(point1)-np.array(point2))**2))